[2024-11-10T18:46:59.180+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: analytics_pipeline.get_dates_for_trip manual__2024-11-10T18:45:56.119673+00:00 [queued]>
[2024-11-10T18:46:59.187+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: analytics_pipeline.get_dates_for_trip manual__2024-11-10T18:45:56.119673+00:00 [queued]>
[2024-11-10T18:46:59.188+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-10T18:46:59.197+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): get_dates_for_trip> on 2024-11-10 18:45:56.119673+00:00
[2024-11-10T18:46:59.201+0000] {standard_task_runner.py:60} INFO - Started process 121 to run task
[2024-11-10T18:46:59.203+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'analytics_pipeline', 'get_dates_for_trip', 'manual__2024-11-10T18:45:56.119673+00:00', '--job-id', '1255', '--raw', '--subdir', 'DAGS_FOLDER/analytics_pipeline.py', '--cfg-path', '/tmp/tmp476_81bx']
[2024-11-10T18:46:59.204+0000] {standard_task_runner.py:88} INFO - Job 1255: Subtask get_dates_for_trip
[2024-11-10T18:46:59.238+0000] {task_command.py:423} INFO - Running <TaskInstance: analytics_pipeline.get_dates_for_trip manual__2024-11-10T18:45:56.119673+00:00 [running]> on host 2a2d16a2b1e8
[2024-11-10T18:46:59.293+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='analytics_pipeline' AIRFLOW_CTX_TASK_ID='get_dates_for_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T18:45:56.119673+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T18:45:56.119673+00:00'
[2024-11-10T18:46:59.310+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/get_dates_for_trip.py", line 49, in get_dates_for_trip
    mongo_hook = MongoHook(conn_id="MongoDB")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mongo/hooks/mongo.py", line 131, in __init__
    conn = self.get_connection(self.mongo_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `MongoDB` isn't defined
[2024-11-10T18:46:59.319+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=analytics_pipeline, task_id=get_dates_for_trip, execution_date=20241110T184556, start_date=20241110T184659, end_date=20241110T184659
[2024-11-10T18:46:59.328+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1255 for task get_dates_for_trip (The conn_id `MongoDB` isn't defined; 121)
[2024-11-10T18:46:59.335+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-10T18:46:59.346+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
